
[functions.wompi-signature]
enabled = true
verify_jwt = false

[functions.wompi-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/wompi-webhook/deno.json"
entrypoint = "./functions/wompi-webhook/index.ts"
